import { BookmarkItem, Collection, Tag } from '@/types/stashr';
import { normalizeTagCollection } from '@/lib/supabase-db';

export interface ValutExportData {
  appName: 'Valut';
  schemaVersion: 1;
  exportedAt: string;
  totalBookmarks: number;
  bookmarks: BookmarkItem[];
  collections: Collection[];
  tags: Tag[];
}

/**
 * Generate full-fidelity JSON export
 */
export function exportVaultToJson(
  bookmarks: BookmarkItem[],
  collections: Collection[] = [],
  tags: Tag[] = []
): string {
  const exportPayload: ValutExportData = {
    appName: 'Valut',
    schemaVersion: 1,
    exportedAt: new Date().toISOString(),
    totalBookmarks: bookmarks.length,
    bookmarks,
    collections,
    tags,
  };

  return JSON.stringify(exportPayload, null, 2);
}

/**
 * Generate clean, human-readable Markdown export compatible with Obsidian, Notion, Logseq
 */
export function exportVaultToMarkdown(
  bookmarks: BookmarkItem[],
  options?: { filterTitle?: string }
): string {
  const now = new Date().toLocaleDateString('en-US', {
    month: 'short',
    day: 'numeric',
    year: 'numeric',
  });

  const lines: string[] = [];

  // Header
  lines.push(`# Valut Knowledge Backup`);
  lines.push(`*Exported on ${now} | Total: ${bookmarks.length} bookmarks*`);
  if (options?.filterTitle) {
    lines.push(`*View: ${options.filterTitle}*`);
  }
  lines.push('');
  lines.push('---');
  lines.push('');

  // Group bookmarks by Platform
  const byPlatform: Record<string, BookmarkItem[]> = {};
  for (const bm of bookmarks) {
    const key = bm.platform || 'web';
    if (!byPlatform[key]) byPlatform[key] = [];
    byPlatform[key].push(bm);
  }

  const platformDisplayNames: Record<string, string> = {
    youtube: '📺 YouTube Videos',
    twitter: '🐦 X / Twitter Posts',
    reddit: '💬 Reddit Discussions',
    instagram: '📸 Instagram Posts',
    github: '💻 GitHub Repositories',
    web: '🌐 Web Articles & Resources',
  };

  for (const [platformKey, items] of Object.entries(byPlatform)) {
    const sectionName = platformDisplayNames[platformKey] || `📌 ${platformKey.toUpperCase()}`;
    lines.push(`## ${sectionName} (${items.length})`);
    lines.push('');

    items.forEach((item, index) => {
      const title = item.title || item.text.slice(0, 70) || 'Untitled Bookmark';
      const link = item.url ? `[${title}](${item.url})` : title;

      lines.push(`### ${index + 1}. ${link}`);
      
      const metaParts: string[] = [];
      if (item.displayName || item.username) {
        metaParts.push(`**Author:** ${item.displayName || ''} (@${item.username || ''})`);
      }
      if (item.date) {
        metaParts.push(`**Date:** ${item.date}`);
      }
      if (metaParts.length > 0) {
        lines.push(metaParts.join(' | '));
      }

      // Tags as hashtags
      if (item.tags && item.tags.length > 0) {
        const tagStrings = item.tags.map(t => `#${t.name.replace(/\s+/g, '_')}`).join(' ');
        lines.push(`**Tags:** ${tagStrings}`);
      }

      // Quote / text
      if (item.text && item.text !== item.title) {
        const quoteText = item.text
          .split('\n')
          .map(line => `> ${line}`)
          .join('\n');
        lines.push(quoteText);
      }

      // Note
      if (item.note) {
        lines.push(`> 📝 **Personal Note:** ${item.note}`);
      }

      lines.push('');
    });

    lines.push('---');
    lines.push('');
  }

  lines.push(`*Generated by Valut Knowledge Vault*`);
  return lines.join('\n');
}

/**
 * Trigger Instant Browser File Download
 */
export function downloadFile(filename: string, content: string, mimeType: string): void {
  if (typeof window === 'undefined') return;

  const blob = new Blob([content], { type: `${mimeType};charset=utf-8;` });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.setAttribute('download', filename);
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}

/**
 * Copy string content to clipboard with fallback
 */
export async function copyToClipboard(text: string): Promise<boolean> {
  if (typeof window === 'undefined') return false;

  try {
    if (navigator.clipboard && window.isSecureContext) {
      await navigator.clipboard.writeText(text);
      return true;
    }
  } catch {}

  try {
    const textArea = document.createElement('textarea');
    textArea.value = text;
    textArea.style.position = 'fixed';
    textArea.style.left = '-999999px';
    textArea.style.top = '-999999px';
    document.body.appendChild(textArea);
    textArea.focus();
    textArea.select();
    const successful = document.execCommand('copy');
    textArea.remove();
    return successful;
  } catch {
    return false;
  }
}

/**
 * Parse and safely validate imported JSON backup
 */
export function parseAndValidateImport(jsonString: string): {
  success: boolean;
  data?: {
    bookmarks: BookmarkItem[];
    collections: Collection[];
    tags: Tag[];
  };
  error?: string;
} {
  try {
    const parsed = JSON.parse(jsonString);

    let rawBookmarks: any[] = [];
    let rawCollections: any[] = [];
    let rawTags: any[] = [];

    // Support both standard Valut backup schema and raw bookmark arrays
    if (Array.isArray(parsed)) {
      rawBookmarks = parsed;
    } else if (parsed && typeof parsed === 'object') {
      if (Array.isArray(parsed.bookmarks)) rawBookmarks = parsed.bookmarks;
      if (Array.isArray(parsed.collections)) rawCollections = parsed.collections;
      if (Array.isArray(parsed.tags)) rawTags = parsed.tags;
    } else {
      return { success: false, error: 'Invalid file format. Expected JSON object or array.' };
    }

    if (rawBookmarks.length === 0) {
      return { success: false, error: 'No bookmarks found in the imported file.' };
    }

    // Validate and sanitize each bookmark
    const validBookmarks: BookmarkItem[] = [];
    const now = new Date().toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' });

    for (const b of rawBookmarks) {
      if (!b || typeof b !== 'object') continue;
      if (!b.url && !b.text && !b.title) continue;

      const validId = b.id && typeof b.id === 'string' ? b.id : `bm_imp_${Date.now()}_${Math.random().toString(36).slice(2, 6)}`;
      const normalizedTags = normalizeTagCollection(Array.isArray(b.tags) ? b.tags : []);

      validBookmarks.push({
        id: validId,
        platform: b.platform || 'web',
        displayName: b.displayName || b.display_name || 'Creator',
        username: b.username ? (String(b.username).startsWith('@') ? String(b.username).slice(1) : String(b.username)) : 'creator',
        avatarUrl: b.avatarUrl || b.avatar_url || undefined,
        imageUrl: b.imageUrl || b.image_url || undefined,
        title: b.title || undefined,
        text: b.text || b.title || b.url || 'Saved Bookmark',
        url: b.url || undefined,
        date: b.date || now,
        createdAt: Number(b.createdAt || b.created_at_ms) || Date.now(),
        tags: normalizedTags,
        isFavorite: Boolean(b.isFavorite || b.is_favorite),
        isArchived: Boolean(b.isArchived || b.is_archived),
        note: b.note || undefined,
        collectionId: b.collectionId || b.collection_id || undefined,
      });
    }

    const validCollections: Collection[] = rawCollections.map((c: any) => ({
      id: c.id || `col_${Date.now()}`,
      name: c.name || 'Untitled Collection',
      icon: c.icon || undefined,
    }));

    const validTags: Tag[] = normalizeTagCollection(rawTags) as Tag[];

    return {
      success: true,
      data: {
        bookmarks: validBookmarks,
        collections: validCollections,
        tags: validTags,
      },
    };
  } catch (err: any) {
    return {
      success: false,
      error: `Could not parse JSON file: ${err.message || 'Syntax error'}`,
    };
  }
}
